import Head from 'next/head'
import { useSession, signOut } from 'next-auth/react'
import { useRouter } from 'next/router'
import Header from '../components/Header'
import Sidebar from '../components/Sidebar'

export default function Home() {
  const { data: session, status } = useSession()
  const router = useRouter()

  if (status === 'loading') return <p>Loading...</p>
  if (status === 'unauthenticated') router.push('/home')
  return (
    <>
      {status === 'authenticated' && (
        <div className="bg-[#f3f2ef] dark:bg-black text-white h-screen overflow-y-scroll md:space-y-6">
          <Head>
            <title>LinkedIn | Feed</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Header />

          <main className="flex justify-center px-4 gap-x-5 sm:px-12">
            <div className="flex flex-col gap-5 md:flex-row gap-x-5">
              <Sidebar />
              {/* Feed */}
            </div>
            {/* Widgets */}
          </main>
        </div>
      )}
    </>
  )
}
